dist: trusty

sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_failure: true
    include:
        - php: 7.3
          env: SYMFONY_VERSION=4.4.x
        - php: 7.4
          env: SYMFONY_VERSION=4.4.x

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo 'memory_limit=-1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi
  - if [ "$stability" != "" ]; then composer config minimum-stability $stability; fi

install:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction; else composer update --prefer-dist --no-interaction; fi;

script: ./vendor/bin/phpunit --coverage-text
